server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
  zipkin:
    base-url: http://microservice-sleuth-server:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@microservice-discovery-eureka:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000